version: '3'

services:
  ProductCatalog:
    build:
      context: ./ProductCatalog
      dockerfile: Dockerfile
    image: productcatalog:1.0.0
    container_name: productcatalog
    ports:
      - "8080:80"

#  OrderProcessing:
#    build:
#      context: ./OrderProcessing
#      dockerfile: Dockerfile
#    image: orderprocessing:1.0.0
#    container_name: orderprocessing
#    ports:
#      - "8081:80"